import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.sass'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import Container from '@/components/Container/Container'

// import { Provider } from 'react-redux'
// import { PersistGate } from 'redux-persist/integration/react'
// import { makeStore, persistor } from '../lib/redux/store' // Adjust the path as needed

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const store = makeStore()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Container>
        {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
            {children}
            <Footer />
          {/* </PersistGate>
        </Provider> */}
        </Container>
      </body>
    </html>
  )
}
